### ISSUE TITLE
Factorio installation not detected on Linux

### ISSUE THREAD

**Issue by remexre** [Arnavion/fac-rs#3]
I think the issue is case-sensitivity -- https://github.com/Arnavion/fac-rs/blob/master/factorio-mods-local/src/api.rs#L185 uses `SteamApps`, where as (my installation of) Steam uses `steamapps`

**Comment by Arnavion** [comment]
Yeah, I don't have a Factorio install on Linux so I've only tested the web API there.

Can you check which one of the paths (if any) in https://github.com/mickael9/fac/blob/401fe28d/fac/files.py#L13-L40 matches your install?

**Comment by remexre** [comment]
None -- the case on `SteamApps` is wrong there too. I think it might be named `SteamApps` on Windows and `steamapps` on Linux, although I don't have a windows install near me to check.

It also looks like fac-rs doesn't search `~/.factorio`, which contains the `mods/mod-list.json` and `player-data.json` files.

**Comment by Arnavion** [comment]
Right, so what's the full path of your Factorio install then?

**Comment by remexre** [comment]
`/home/nathan/.local/share/Steam/steamapps/common/Factorio` is the static files, `/home/nathan/.factorio` is the per-user data

**Comment by remexre** [comment]
I patched it to add `~/factorio` and `~/.factorio` to the search path and fix the capitalization, but now it dies because `mod_list.json` uses the string `"true"` instead of the boolean `true` for `"enabled"`.

**Comment by Arnavion** [comment]
The `true` vs `"true"` is a change in 0.15 I believe. I changed it in https://github.com/Arnavion/fac-rs/commit/ad35af38

**Comment by remexre** [comment]
I just deleted `~/.factorio`, disabled Steam Cloud Sync, and started the game, and `~/.factorio/mods/mod-list.json` was created with the contents:

```json
{
    "mods": [
        {
            "name": "base",
            "enabled": "true"
        }
    ]
}
```

One solution would be to use `#[serde(deserialize_with = "path")]` to make a custom deserializer that accepts either a bool or a string, I guess.

**Comment by remexre** [comment]
It looks like `cfg!(linux)` isn't actually a thing -- `cfg!(target_os = "linux")` works, though.

**Comment by Arnavion** [comment]
`deserialize_with` may not be enough, since when it writes the file back it'll write the values as booleans even if they were originally strings. Just to confirm, you're on 0.14 right? Can you check if the game is able to load mod-list.json with boolean values instead of string values?

**Comment by remexre** [comment]
I'm on version 0.14.23, build 25374, and it's working as far as I can tell with plain `bool`. **EDIT**: The game does change it back to `"true"` on exit, though.
